use_frameworks!
target 'MiniProjet'
pod 'GoogleSignIn'
pod 'Alamofire'
pod 'Cosmos', '~> 23.0'
pod 'TinyConstraints'

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
